name: Quiz_App
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.1
  assets_audio_player: ^2.0.8+4
  shared_preferences: ^0.5.8
  circular_countdown_timer: ^0.0.4
  




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/mainMenu.jpg
   - images/playScreen.jpg
   - images/states/alabama_al.png
   - images/states/alaska_ak.png
   - images/states/arizona_az.png
   - images/states/arkansas_ar.png
   - images/states/california_ca.png
   - images/states/colorado_co.png
   - images/states/connenticut_ct.png
   - images/states/delaware_de.png
   - images/states/florida_fl.png
   - images/states/georgia_ga.png
   - images/states/hawaii_hi.png
   - images/states/idaho_id.png
   - images/states/illinois_il.png
   - images/states/indiana_in.png
   - images/states/iowa_ia.png
   - images/states/kansas_ks.png
   - images/states/kentukey_ky.png
   - images/states/louisiana_la.png
   - images/states/maine_me.png
   - images/states/maryland_md.png
   - images/states/massachusetts_ma.png
   - images/states/michigan_mi.png
   - images/states/minnesota_mn.png
   - images/states/mississippi_ms.png
   - images/states/missouri_mo.png
   - images/states/montana_mt.png
   - images/states/nebraska_ne.png
   - images/states/nevada_nv.png
   - images/states/new_hampshire.png
   - images/states/new_jersey.png
   - images/states/new_mexico.png
   - images/states/new_york.png
   - images/states/north_carolina.png
   - images/states/north_dakota.png
   - images/states/ohaio_oh.png
   - images/states/oklahoma_ok.png
   - images/states/oregon_or.png
   - images/states/pennsylvania_pa.png
   - images/states/rhode_island.png
   - images/states/south_carolina.png
   - images/states/south_dakota.png
   - images/states/tennessee_tn.png
   - images/states/texas_tx.png
   - images/states/utah_ut.png
   - images/states/vermont_vt.png
   - images/states/virginia_va.png
   - images/states/washington_wa.png
   - images/states/west_virginia.png
   - images/states/wisconsin_wi.png
   - images/states/wyoming_wy.png
   - sounds/wrong.mp3
   - sounds/correct.mp3
   - images/rewards.jpg
   - images/gameModeScreen.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: MrsSheppards
       fonts:
         - asset: fonts/MrsSheppards-Regular.ttf

     - family: Nisebuschgardens
       fonts:
         - asset: fonts/Nisebuschgardens-wqK8.ttf

     - family: volkswagen-serial
       fonts: 
         - asset: fonts/volkswagen-serial-bold.ttf

     - family: Digitalt
       fonts: 
         - asset: fonts/Digitalt-04no.ttf 

     - family: KronaOne
       fonts: 
         - asset: fonts/KronaOne-Regular.ttf 

     - family: AmericanDream
       fonts: 
         - asset: fonts/AmericanDream-1v9j.ttf          


         
         
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
